// lib/data.js
export const data = [
  {
    id: 1,
    week: 'Week : 1',
    date: 'Jan 1, 2025',
    day: 'Wednesday',
    platform: 'All',
    theme: 'Happy New Year!',
    format: 'Image/Video',
    description:
      'Festive post wishing a Happy New Year. Mention resolutions to improve online presence and how OctaVertex Media can help achieve those goals.',
    cta: '',
    hashtags: ['#HappyNewYear', '#2025', '#OctaVertexMedia', '#DigitalMarketingGoals', '#NewYearNewWebsite'],
    uploadedContent: null,
  },
  {
    id: 2,
    week: 'Week : 1',
    date: 'Jan 2, 2025',
    day: 'Thursday',
    platform: 'Instagram',
    theme: 'Web Design Showcase',
    format: 'Image Carousel',
    description:
      'Showcase a recent website design project. Highlight key features like responsive design, user-friendly interface, and SEO optimization.',
    cta: 'Get a free website audit!',
    hashtags: ['#WebDesign', '#WebsiteShowcase', '#ResponsiveDesign', '#UXDesign', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 3,
    week: 'Week : 1',
    date: 'Jan 2, 2025',
    day: 'Thursday',
    platform: 'LinkedIn',
    theme: 'SEO Tip of the Week',
    format: 'Text/Image',
    description:
      'Share a valuable SEO tip, such as the importance of keyword research or optimizing meta descriptions. Explain how it impacts search engine rankings.',
    cta: 'Learn more about our SEO services!',
    hashtags: ['#SEOTips', '#KeywordResearch', '#MetaDescriptions', '#SEOServices', '#DigitalMarketing', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 4,
    week: 'Week : 1',
    date: 'Jan 3, 2025',
    day: 'Friday',
    platform: 'Twitter',
    theme: 'Social Media Engagement Poll',
    format: 'Poll',
    description:
      'Ask your audience which social media platform they find most challenging to manage. Offer tips in the comments for each platform.',
    cta: 'Contact us for social media help!',
    hashtags: ['#SocialMediaMarketing', '#SocialMediaPoll', '#Engagement', '#SMM', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 5,
    week: 'Week : 1',
    date: 'Jan 4, 2025',
    day: 'Saturday',
    platform: 'Facebook',
    theme: 'Client Testimonial',
    format: 'Video',
    description:
      'Share a short video testimonial from a satisfied client who benefited from your content creation services.',
    cta: 'Let us create your content!',
    hashtags: ['#ClientSuccess', '#ContentCreation', '#VideoTestimonial', '#ContentMarketing', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 6,
    week: 'Week : 1',
    date: 'Jan 5, 2025',
    day: 'Sunday',
    platform: 'Instagram',
    theme: 'Graphic Design Inspiration',
    format: 'Image',
    description:
      'Share a visually appealing graphic design piece (e.g., a logo, infographic, or social media graphic) that your team created.',
    cta: 'Get a custom design quote!',
    hashtags: ['#GraphicDesign', '#VisualContent', '#LogoDesign', '#Infographic', '#DesignInspiration', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 7,
    week: 'Week : 1',
    date: 'Jan 6, 2025',
    day: 'Monday',
    platform: 'All',
    theme: 'Blog Post Promotion',
    format: 'Image/Link',
    description:
      'Promote a new blog post on your website about "5 E-commerce Trends to Watch in 2025". Include a compelling image and a link to the blog post.',
    cta: 'Read the full article!',
    hashtags: ['#Ecommerce', '#EcommerceTrends', '#OnlineStore', '#DigitalMarketingBlog', '#OctaVertexMedia', '#WebDevelopment'],
    uploadedContent: null,
  },
  {
    id: 8,
    week: 'Week : 2',
    date: 'Jan 7, 2025',
    day: 'Tuesday',
    platform: 'LinkedIn',
    theme: 'Website Redesign: Before & After',
    format: 'Image/Article',
    description:
      'Showcase a website redesign project, highlighting the improvements in design, functionality, and user experience.',
    cta: 'Ready for a website makeover?',
    hashtags: ['#WebsiteRedesign', '#BeforeAndAfter', '#WebDev', '#UX', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 9,
    week: 'Week : 2',
    date: 'Jan 8, 2025',
    day: 'Wednesday',
    platform: 'Instagram',
    theme: 'Importance of Mobile-Friendly',
    format: 'Video/Reels',
    description:
      'Short video explaining why mobile-friendly websites are crucial in today\'s digital landscape.',
    cta: 'Check if your website is mobile-friendly',
    hashtags: ['#MobileFriendly', '#ResponsiveDesign', '#WebDesignTips', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 10,
    week: 'Week : 2',
    date: 'Jan 9, 2025',
    day: 'Thursday',
    platform: 'Twitter',
    theme: 'Local SEO Benefits',
    format: 'Text/Image',
    description: 'Discuss how local SEO helps businesses attract customers in their area.',
    cta: 'Boost your local visibility',
    hashtags: ['#LocalSEO', '#SEOTips', '#SmallBusiness', '#DigitalMarketing', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 11,
    week: 'Week : 2',
    date: 'Jan 10, 2025',
    day: 'Friday',
    platform: 'Facebook',
    theme: 'Google Ads Success Story',
    format: 'Case Study/Image',
    description:
      'Share a client success story using Google Ads, highlighting the positive results achieved.',
    cta: 'Drive results with Google Ads',
    hashtags: ['#GoogleAds', '#SEM', '#CaseStudy', '#MarketingSuccess', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 12,
    week: 'Week : 2',
    date: 'Jan 11, 2025',
    day: 'Saturday',
    platform: 'Instagram',
    theme: 'Instagram Story Strategies',
    format: 'Story Series',
    description:
      'Provide tips on creating engaging Instagram Stories, using interactive features, and running effective Story ads.',
    cta: 'Level up your Instagram game',
    hashtags: ['#InstagramStories', '#StoryIdeas', '#SocialMediaTips', '#SMM', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 13,
    week: 'Week : 2',
    date: 'Jan 12, 2025',
    day: 'Sunday',
    platform: 'All',
    theme: 'The Power of Video Marketing',
    format: 'Video/Blog Post',
    description:
      'Discuss the impact of video marketing on brand awareness, engagement, and conversions. Showcase your video production capabilities.',
    cta: 'Tell your story with video',
    hashtags: ['#VideoMarketing', '#ContentMarketing', '#VideoProduction', '#DigitalStrategy', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 14,
    week: 'Week : 2',
    date: 'Jan 13, 2025',
    day: 'Monday',
    platform: 'LinkedIn',
    theme: 'Building a LinkedIn Content Strategy',
    format: 'Article',
    description:
      'Share tips on creating a strong content strategy for LinkedIn to build a professional network and establish thought leadership.',
    cta: 'Connect with us on LinkedIn',
    hashtags: ['#LinkedInMarketing', '#ContentStrategy', '#B2BMarketing', '#ProfessionalNetworking', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 15,
    week: 'Week : 3',
    date: 'Jan 14, 2025',
    day: 'Tuesday',
    platform: 'Twitter',
    theme: 'Social Media Content Calendar Tips',
    format: 'Text/Image',
    description:
      'Offer advice on how to create and maintain a consistent social media content calendar.',
    cta: 'Need help with content planning?',
    hashtags: ['#SocialMediaCalendar', '#ContentPlanning', '#SMTips', '#MarketingTips', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 16,
    week: 'Week : 3',
    date: 'Jan 15, 2025',
    day: 'Wednesday',
    platform: 'Instagram',
    theme: 'Blog Writing Best Practices',
    format: 'Image/Carousel',
    description:
      'Share tips on writing engaging and SEO-friendly blog posts that attract readers and drive traffic.',
    cta: 'Need compelling blog content?',
    hashtags: ['#BlogWriting', '#ContentWriting', '#SEOWriting', '#BloggingTips', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 17,
    week: 'Week : 3',
    date: 'Jan 16, 2025',
    day: 'Thursday',
    platform: 'Facebook',
    theme: 'Repurposing Content',
    format: 'Infographic/Link',
    description:
      'Show examples of how a single piece of content can be repurposed into different formats for various social media platforms.',
    cta: 'Maximize your content\'s reach',
    hashtags: ['#ContentRepurposing', '#ContentStrategy', '#MarketingHacks', '#DigitalMarketing', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 18,
    week: 'Week : 3',
    date: 'Jan 17, 2025',
    day: 'Friday',
    platform: 'LinkedIn',
    theme: 'Importance of a Strong Brand',
    format: 'Article',
    description:
      'Discuss the key elements of a strong brand identity and how it helps businesses stand out.',
    cta: 'Define your brand',
    hashtags: ['#BrandIdentity', '#Branding', '#MarketingStrategy', '#BusinessTips', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 19,
    week: 'Week : 3',
    date: 'Jan 18, 2025',
    day: 'Saturday',
    platform: 'Instagram',
    theme: 'Logo Design Trends',
    format: 'Image Gallery',
    description: 'Showcase current and upcoming logo design trends.',
    cta: 'Get a modern logo',
    hashtags: ['#LogoDesign', '#DesignTrends', '#GraphicDesign', '#Branding', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 20,
    week: 'Week : 3',
    date: 'Jan 19, 2025',
    day: 'Sunday',
    platform: 'All',
    theme: 'Creating a Marketing Strategy',
    format: 'Checklist/Guide',
    description:
      'Offer a downloadable checklist or guide to help businesses plan their marketing strategy for the new year.',
    cta: 'Plan for success in 2025',
    hashtags: ['#MarketingStrategy', '#2025Planning', '#MarketingGuide', '#DigitalMarketing', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 21,
    week: 'Week : 3',
    date: 'Jan 20, 2025',
    day: 'Monday',
    platform: 'Twitter',
    theme: 'Understanding SEO Audits',
    format: 'Text/Link',
    description:
      'Explain what an SEO audit is, why it\'s important, and what insights it provides.',
    cta: 'Get a comprehensive SEO audit',
    hashtags: ['#SEOAudit', '#SEO', '#WebsiteAnalysis', '#DigitalMarketingTips', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 22,
    week: 'Week : 4',
    date: 'Jan 21, 2025',
    day: 'Tuesday',
    platform: 'Instagram',
    theme: 'App Design Best Practices',
    format: 'Image/Carousel',
    description: 'Share tips on designing user-friendly and visually appealing mobile apps.',
    cta: 'Get a beautifully designed app',
    hashtags: ['#AppDesign', '#MobileApp', '#UIUXDesign', '#AppDevelopment', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 23,
    week: 'Week : 4',
    date: 'Jan 22, 2025',
    day: 'Wednesday',
    platform: 'Facebook',
    theme: 'Optimizing Product Pages',
    format: 'Infographic',
    description:
      'Share tips on how to optimize e-commerce product pages to increase conversions (e.g., high-quality images, compelling descriptions, reviews).',
    cta: 'Boost your online sales',
    hashtags: ['#Ecommerce', '#ProductPages', '#ConversionOptimization', '#OnlineStore', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 24,
    week: 'Week : 4',
    date: 'Jan 23, 2025',
    day: 'Thursday',
    platform: 'LinkedIn',
    theme: 'Choosing the Right E-commerce Platform',
    format: 'Article/Chart',
    description:
      'Compare different e-commerce platforms (e.g., Shopify, WooCommerce, Magento) to help businesses choose the right one for their needs.',
    cta: 'Find the perfect platform for your store',
    hashtags: ['#EcommercePlatforms', '#Shopify', '#WooCommerce', '#Magento', '#OnlineBusiness', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 25,
    week: 'Week : 4',
    date: 'Jan 24, 2025',
    day: 'Friday',
    platform: 'Twitter',
    theme: 'Website Security Tips',
    format: 'Text/Image',
    description:
      'Share tips on how businesses can improve their website security (e.g., strong passwords, updates, SSL certificates).',
    cta: 'Protect your website',
    hashtags: ['#WebsiteSecurity', '#Cybersecurity', '#WebDev', '#OnlineSafety', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 26,
    week: 'Week : 4',
    date: 'Jan 25, 2025',
    day: 'Saturday',
    platform: 'Instagram',
    theme: 'Behind the Scenes: Design Process',
    format: 'Video/Story',
    description:
      'Show a behind-the-scenes look at your graphic design process, from initial concept to final product.',
    cta: 'See our creativity in action',
    hashtags: ['#GraphicDesign', '#DesignProcess', '#BehindTheScenes', '#CreativeAgency', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 27,
    week: 'Week : 4',
    date: 'Jan 26, 2025',
    day: 'Sunday',
    platform: 'All',
    theme: 'Client Case Study: Brand Refresh',
    format: 'Case Study/Images',
    description:
      'Showcase a successful brand refresh project you completed for a client, highlighting the positive impact on their business.',
    cta: 'Is your brand ready for a refresh?',
    hashtags: ['#BrandRefresh', '#CaseStudy', '#BrandingSuccess', '#MarketingResults', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 28,
    week: 'Week : 4',
    date: 'Jan 27, 2025',
    day: 'Monday',
    platform: 'LinkedIn',
    theme: 'Benefits of a Mobile App',
    format: 'Article',
    description:
      'Explain how having a mobile app can benefit businesses (e.g., increased engagement, brand loyalty, new revenue streams).',
    cta: 'Reach your customers on the go',
    hashtags: ['#MobileApp', '#AppBenefits', '#AppDevelopment', '#BusinessGrowth', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 29,
    week: 'Week : 4',
    date: 'Jan 28, 2025',
    day: 'Tuesday',
    platform: 'Instagram',
    theme: 'Ecommerce Email Marketing Strategies',
    format: 'Video/Carousel',
    description:
      'Share effective e-commerce email marketing strategies, such as abandoned cart emails, promotional campaigns, and personalized recommendations.',
    cta: 'Drive sales with email marketing',
    hashtags: ['#EmailMarketing', '#EcommerceTips', '#MarketingAutomation', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 30,
    week: 'Week : 4',
    date: 'Jan 29, 2025',
    day: 'Wednesday',
    platform: 'Facebook',
    theme: 'App Development Process',
    format: 'Blog Post/Link',
    description:
      'Outline the different stages of your app development process, from concept and planning to design, development, testing, and launch.',
    cta: 'Turn your app idea into reality',
    hashtags: ['#AppDevelopmentProcess', '#MobileAppDev', '#AppDesign', '#TechSolutions', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 31,
    week: 'Week : 4',
    date: 'Jan 30, 2025',
    day: 'Thursday',
    platform: 'Twitter',
    theme: 'Importance of Visual Consistency',
    format: 'Text/Image',
    description:
      'Discuss the importance of maintaining visual consistency across all marketing materials to build brand recognition and trust.',
    cta: 'Ensure brand consistency',
    hashtags: ['#VisualConsistency', '#BrandGuidelines', '#GraphicDesign', '#MarketingMaterials', '#OctaVertexMedia'],
    uploadedContent: null,
  },
  {
    id: 32,
    week: 'Week : 4',
    date: 'Jan 31, 2025',
    day: 'Friday',
    platform: 'All',
    theme: 'January Recap',
    format: 'Image/Video',
    description:
      "A quick recap of January's highlights, top-performing posts, and a thank you to your audience.",
    cta: '',
    hashtags: ['#JanuaryRecap', '#MarketingHighlights', '#ThankYou', '#OctaVertexMedia', '#2025'],
    uploadedContent: null,
  },
];